version: "3"
services:
  nodestatus:
    image: cokemine/nodestatus
    restart: always

    environment:
      PORT: 35601
      VERBOSE: "false"
      THEME: "hotaru-theme"

      USE_PUSH: "true"
      USE_IPC: "true"
      USE_WEB: "true"

      WEB_USERNAME: "admin"
      WEB_PASSWORD: "123456"
      WEB_SECRET: ""
      DATABASE: "postgresql://okteto:okteto@127.0.0.1:5432/okteto"


      PUSH_TIMEOUT: 30
      PUSH_DELAY: 15
      TGBOT_TOKEN: ""
      TGBOT_CHATID: ""
      TGBOT_PROXY: ""
      TGBOT_WEBHOOK: ""

    volumes:
      - /usr/local/NodeStatus/server:/usr/local/NodeStatus/server
      - /tmp:/tmp:rw

    ports:
      - "35601:35601"

